import boto3
import check_vpc
from botocore.exceptions import ClientError
#
zql_private_security_group_id = 'sg-128e646b'
zql_public_security_group_id = 'sg-dd8c66a4'
zql_office_security_group_id = 'sg-958f65ec'
zql_resource_security_group_id = 'sg-478a603e'
bnb_office_security_group_id = 'sg-8adf98ec'
bnb_public_security_group_id = 'sg-76de9910'
bnb_private_security_group_id = 'sg-c3d295a5'
bnb_kr_public_security_group_id = 'sg-86e34ced'
dae_private_security_group_id = 'sg-7fcdc719'
dae_public_security_group_id = 'sg-a1cdc7c7'
dae_office_security_group_id = 'sg-53c1cb35'
dae_resource_security_group_id = 'sg-56ced430'

